import {
  AmusementParkModel,
  AquariumModel,
  BikingModel,
  ConcertModel,
  DiningModel,
  FlightModel,
  GolfModel,
  HikingModel,
  HotelModel,
  MuseumModel,
  NightlifeModel,
  ParkModel,
  ShoppingModel,
  SpaModel,
  SportsModel,
  TheatreModel,
  WaterparkModel,
  ZooModel
} from "@/models";

export const modelTypes = {
  Hotel: HotelModel,
  Dining: DiningModel,
  Flight: FlightModel,
  Theatre: TheatreModel,
  Concert: ConcertModel,
  Museum: MuseumModel,
  Park: ParkModel,
  Zoo: ZooModel,
  Spa: SpaModel,
  Golf: GolfModel,
  Aquarium: AquariumModel,
  Hiking: HikingModel,
  Biking: BikingModel,
  Waterpark: WaterparkModel,
  AmusementPark: AmusementParkModel,
  Sports: SportsModel,
  Nightlife: NightlifeModel,
  Shopping: ShoppingModel
};
