#!/bin/bash
FILE=.built
start=1
build=0
validate=0
test=0
help=0


while [[ "$#" -gt 0 ]]; do
    case $1 in
        -b|--rebuild) build=1;;
        -v|--validate) validate=1;;
        -t|--test) test=1;;
        -h|--help) help=1;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

if [[ $help == 1 ]]; then
    echo
    echo "$0 [-bs]|[--build|start]"
    echo
    echo ' Builds and runs the Docker container.'
    echo
    echo "-------------------------------------------------"
    echo
    echo "Options:"
    echo
    echo "  -b | --rebuild      : Update package dependencies."
    echo "  -v | --validate     : Validate the build for pull request."
    echo "  -t | --test         : Run vitest."
    echo
    echo "-------------------------------------------------"
    echo
    echo "Note: Can be specified for individual operations."
    exit 1

fi

f=''
b=''

if [[ $start == 1 ]]; then
    if [[ $build == 1 ]]; then
        b='--build'
    elif [[ $validate == 1 ]]; then
        f='-f ./docker-compose.validate.yml'
        b='--build'
    elif [[ $test == 1 ]]; then
        f='-f ./docker-compose.test.yml'
        b='--build'
    fi;
    docker compose $f up $b --force-recreate -V
fi;

docker compose down -v
