import { Shopping } from "@/types/Event";
import { faker } from "@faker-js/faker";
import { randomInt } from "crypto";
import {
  nameAndRandomDescriptions,
  openingHours,
  randomWordList,
  roundedFloat
} from "../utils";

/** Generate a random shopping activity. */
export const shopping = (): Shopping => {
  const storeNames = [
    "Fashion Fusion",
    "Tech Haven",
    "Cosmic Trends",
    "Sole Sensation",
    "Gourmet Delights",
    "Style Symphony",
    "Gadget Galaxy",
    "Vogue Vault",
    "Urban Charm",
    "Electro Elegance",
    "Chic Boutique",
    "Gourmet Glory",
    "Luxe Lane",
    "Dazzle Den",
    "Savor Square",
    "Urban Outfits",
    "Tech Terrace",
    "Glitter Galleria",
    "Foodie Fiesta",
    "Elegance Emporium",
    "Sleek Styles",
    "Smart Select",
    "Gourmet Grove",
    "Trendy Trinkets",
    "Flavor Fusion",
    "Epic Elegance",
    "Gadget Garden",
    "Charm City",
    "Gourmet Gateway",
    "Style Sanctuary",
    "Electro Essence",
    "Trend Trance",
    "Gastronomy Grove",
    "Couture Corner",
    "Tech Treasure",
    "Chic Chicane",
    "Gourmet Galore",
    "Urban Utopia",
    "Vivid Vogue",
    "Taste Trail",
    "Epicurean Enclave",
  ];

  const stores = randomWordList(storeNames);

  const customerReviews = () => {
    const names = [
      "John Doe",
      "Jane Doe",
      "John Smith",
      "Jane Smith",
      "James Smith",
      "James Doe",
      "Michael Smith",
      "Michael Doe",
      "Robert Smith",
      "Robert Doe",
      "William Smith",
      "William Doe",
      "David Smith",
      "David Doe",
      "Richard Smith",
      "Richard Doe",
      "Joseph Smith",
      "Joseph Doe",
      "Thomas Smith",
      "Thomas Doe",
      "Charles Smith",
      "Charles Doe",
      "Christopher Smith",
      "Christopher Doe",
      "Daniel Smith",
      "Daniel Doe",
      "Matthew Smith",
      "Matthew Doe",
      "Anthony Smith",
      "Anthony Doe",
      "Donald Smith",
      "Donald Doe",
      "Mark Smith",
      "Mark Doe",
      "Paul Smith",
      "Paul Doe",
      "Steven Smith",
      "Steven Doe",
      "Andrew Smith",
      "Andrew Doe",
      "Kenneth Smith",
      "Kenneth Doe",
      "Joshua Smith",
      "Joshua Doe",
      "Kevin Smith",
      "Kevin Doe",
      "Brian Smith",
      "Brian Doe",
      "George Smith",
      "George Doe",
      "Edward Smith",
      "Edward Doe",
      "Ronald Smith",
      "Ronald Doe",
      "Timothy Smith",
      "Timothy Doe",
      "Jason Smith",
      "Jason Doe",
      "Jeffrey Smith",
      "Jeffrey Doe",
      "Ryan Smith",
      "Ryan Doe",
      "Jacob Smith",
      "Jacob Doe",
      "Gary Smith",
      "Gary Doe",
      "Nicholas Smith",
      "Nicholas Doe",
      "Eric Smith",
      "Eric Doe",
      "Jonathan Smith",
      "Jonathan Doe",
      "Stephen Smith",
      "Stephen Doe",
      "Larry Smith",
      "Larry Doe",
      "Justin Smith",
      "Justin Doe",
      "Scott Smith",
      "Scott Doe",
      "Brandon Smith",
      "Brandon Doe",
      "Frank Smith",
      "Frank Doe",
      "Benjamin Smith",
      "Benjamin Doe",
      "Gregory Smith",
      "Gregory Doe",
      "Samuel Smith",
      "Samuel Doe",
      "Raymond Smith",
    ];
    const reviews = {} as any;

    for (let i = 0; i < randomInt(2, 20); i++) {
      reviews[names[randomInt(names.length)]] = {
        store: stores[randomInt(stores.length)],
        rating: roundedFloat(1, 5),
        comment: faker.lorem.words(),
      };
    }

    return reviews;
  };

  return {
    mall: faker.company.name(),
    stores,
    openingHours: openingHours(),
    salesAndDeals: nameAndRandomDescriptions([
      "Buy One, Get One Free",
      "Clearance",
      "Flash Sale",
      "Limited-Time Offers",
      "Doorbuster Deals",
      "Discount Bonanza",
      "Seasonal Specials",
      "Bundle and Save",
      "Early Bird Discounts",
      "Weekend Blowout",
      "Midnight Madness",
      "Holiday Extravaganza",
      "Exclusive Online Deals",
      "Student Discounts",
      "Senior Citizen Savings",
      "Cashback Rewards",
      "Refer a Friend Discounts",
      "Loyalty Program Benefits",
      "Daily Deals",
      "Cyber Monday Bargains",
      "Black Friday Spectacular",
      "Warehouse Clearance",
      "Last Chance Savings",
      "BOGO 50% Off",
      "Member-Only Discounts",
      "Anniversary",
      "App-Only Offers",
      "Free Shipping on Orders Over $50",
      "Gift with Purchase",
      "Price Drop Alerts",
      "Email Subscriber Exclusives",
      "VIP Previews",
      "Outlet Store Discounts",
      "Savings Spectacle",
      "Major Markdowns",
      "Bundle Bash",
      "Clearance Countdown",
      "Mega Discounts Marathon",
      "Buy More, Save More",
      "Open-Box Specials",
      "End-of-Season Clearance",
      "New Customer Welcome Discounts",
      "Daily Steals",
      "Online Only Deals",
      "BOGO 30% Off",
      "Reward Points Redemption",
      "Summer Savings Spree",
      "Autumn Harvest Deals",
      "Winter Wonderland Discounts",
      "Spring Fling Savings",
      "Deal of the Day",
      "Extra 20% Off Items",
      "Sizzling Hot Offers",
      "Mobile App Madness",
      "In-Store Exclusive Deals",
      "Frequent Shopper Rewards",
      "Coupon Extravaganza",
      "Secret for Subscribers",
      "Buy Now, Pay Later Options",
      "Digital Download Discounts",
      "Limited Quantity Deals",
      "Apparel Clearance",
      "Tech Tuesday Discounts",
      "Home Essentials",
      "Sports and Outdoor Deals",
      "Beauty Bonanza",
      "Healthy Living Discounts",
      "Entertainment Extravaganza",
      "Travel and Adventure Savings",
      "Pet Paradise Deals",
      "Gourmet Delights Discounts",
      "Kids' Corner Savings",
      "DIY and Home Improvement Offers",
      "Bookworm Bargains",
      "Gaming Galore Discounts",
      "Fashion Forward",
      "Fitness and Wellness Deals",
      "Car Enthusiast Specials",
      "Electronics Expo Discounts",
    ]),
    diningOptions: nameAndRandomDescriptions([
      "Bistro Bliss",
      "Gourmet Grains",
      "Culinary Canvas",
      "Savory Spice Lounge",
      "The Olive Branch",
      "Flavors of Fusion",
      "Street Food Haven",
      "Pasta Paradise",
      "Ethnic Eats Express",
      "The Grill Spot",
      "Sweet Treats Delight",
      "Healthful Harvest",
      "Brews and Bites",
      "Global Gourmet Hub",
      "Sizzling Sushi Shack",
      "Vegetarian Visions",
      "Mouthwatering Munchies",
      "Deli Delight",
      "Crispy Crust Pizzeria",
      "Fresh and Fast Fare",
      "Wok Wonders",
      "Bakery Bliss",
      "Tasty Tandoor",
      "Seafood Sensations",
      "Grains and Greens Galore",
      "Munchies Corner",
      "The Cheesecake Haven",
      "Smoothie Sanctuary",
      "Juice Joint",
      "Wrap and Roll",
      "Taco Temptations",
      "Noodle Nirvana",
      "Healthy Harvest Bowl",
      "Burger Bistro",
      "Sweet Sensations Bakery",
      "Fruit Fusion",
      "Cheesy Delights",
      "Crepes and Coffee Corner",
      "Sip and Savor Lounge",
      "Bagel Bliss",
      "Candy Carnival",
      "Doughnut Delights",
      "Yogurt Yum",
      "Gelato Grove",
      "Bubble Tea Boutique",
      "Gourmet Gelateria",
      "Chocolate Delights",
      "Dessert Dreamland",
    ]),
    customerReviews: customerReviews(),
    shoppingBudget: roundedFloat(1, 10000),
  };
};
