export const spas = [
  "Serenity Spa Retreat",
  "Tranquil Oasis Wellness Center",
  "Blissful Escapes Spa",
  "Elysian Fields Spa & Resort",
  "Harmony Haven Spa",
  "Zenith Wellness Spa",
  "Pure Indulgence Day Spa",
  "Heavenly Retreat Spa",
  "Radiant Tranquility Spa",
  "Aqua Serene Spa",
  "Revitalize Wellness Spa",
  "Relaxation Haven Spa",
  "Soothing Waters Spa",
  "Essence of Calmness Spa",
  "Sanctuary Spa and Salon",
  "Inner Harmony Spa",
  "The Zen Den Spa",
  "Nature's Rejuvenation Spa",
  "Tranquility Time Spa",
  "Celestial Serenity Spa"
];

export const packages = [
  "Relaxation Retreat",
  "Couples Bliss Package",
  "Detox and Renewal",
  "Pampering Paradise",
  "Tranquil Tranformation",
  "Holistic Harmony",
  "Aromatherapy Delight",
  "Skin Rejuvenation Escape",
  "Stress-Free Serenity",
  "Wellness Wonderland"
];

export const wellnessClasses = [
  "Yoga Basics",
  "Meditation and Mindfulness",
  "Pilates Fusion",
  "Tai Chi for Beginners",
  "Holistic Nutrition Workshop",
  "Stress Reduction Seminar",
  "Zumba Fitness Party",
  "Guided Nature Walk",
  "Breathing Techniques Workshop",
  "Mind-Body Connection Class"
];

export const services = [
  "Swedish Massage",
  "Deep Tissue Massage",
  "Hot Stone Therapy",
  "Aromatherapy Massage",
  "Facial Rejuvenation",
  "Body Scrub and Wrap",
  "Manicure and Pedicure",
  "Couples Massage",
  "Reflexology",
  "Hydrotherapy"
];

export const Concerts = [
  "Rhythmic Fusion Fest",
  "Harmony in the Hills",
  "Rock Revolution",
  "Jazz Nights Extravaganza",
  "Pop Mania",
  "Electric Symphony Showcase",
  "Soulful Serenade",
  "Country Beats Carnival",
  "Indie Vibes Unplugged",
  "Hip-hop Fusion Fiesta",
  "Classical Crescendo",
  "Reggae Rhythms Rendezvous",
  "Acoustic Melodies Soiree",
  "EDM Galaxy Gala",
  "Alternative Anthem",
  "Blues Blast",
  "Folk Fusion Fiesta",
  "Metal Madness Concert",
  "Latin Groove Explosion",
  "World Music Extravaganza"
];

export const SportType = [
  "Football",
  "Baseball",
  "Basketball",
  "Hockey",
  "Soccer",
  "Tennis"
] as const;

export type TSportType = (typeof SportType)[number];

export const ClubType = [
  "Nightclub",
  "Lounge",
  "Bar",
  "Pub",
  "Karaoke Bar",
  "Wine Bar",
  "Sports Bar",
  "Dance Club",
  "Jazz Club",
  "Comedy Club",
  "Irish Pub",
  "Cocktail Bar",
  "Live Music Venue",
  "Rooftop Bar",
  "Speakeasy",
  "Beer Garden",
  "Hookah Lounge",
  "Casino",
  "Billiards Hall",
  "Brewery",
  "Cabaret",
  "Gastropub",
  "Salsa Club",
  "Piano Bar",
  "Tiki Bar",
  "Country Bar",
  "Electronic Dance Club (EDM)",
  "Latin Club",
  "Rhythm and Blues (R&B) Venue",
  "Reggae Club",
  "Hip Hop Club",
  "Alternative Music Venue",
  "Folk Music Venue",
  "Indie Rock Venue",
  "K-pop Club",
  "Arcade Bar",
  "Themed Nightclub",
  "Upscale Lounge",
  "Dive Bar",
  "Biker Bar",
  "Gay Bar",
  "Lesbian Bar",
  "Craft Cocktail Bar",
  "Late-Night Diner",
  "Outdoor Beer Garden",
  "Soul Music Venue",
  "Funk Club",
  "Discotheque",
  "Tapas Bar",
  "Gin Bar",
  "Vodka Bar",
  "Sake Bar",
  "Whiskey Bar",
  "Rum Bar",
  "Tequila Bar",
  "Cigar Lounge",
  "Kareoke Lounge",
  "Happy Hour Spot",
  "Rave",
  "Electronic Music Festival",
  "After-Hours Club",
  "VIP Club"
] as const;

export type TClubType = (typeof ClubType)[number];

export const DressCode = [
  "Casual Chic",
  "Smart Casual",
  "Cocktail Attire",
  "Business Casual",
  "Dress to Impress",
  "Upscale Casual",
  "Glamorous Evening Wear",
  "Beach Elegant",
  "Creative Black Tie",
  "Vintage Glam",
  "Fashion Forward",
  "Bohemian Chic",
  "Urban Sophistication",
  "Resort Casual",
  "Funky and Eclectic",
  "White Party Attire",
  "High Fashion",
  "Red Carpet Ready",
  "Laid-Back Lounge Wear",
  "Retro Revival",
  "Tropical Vibes",
  "Edgy Street Style",
  "Athleisure Elegance",
  "Formal Funk",
  "Eclectic Mix and Match",
  "City Sleek",
  "Dapper and Dashing",
  "Gothic Glam",
  "Festival Fashion",
  "Island Vibes",
  "Denim and Diamonds",
  "Artistic Expression",
  "Vintage Hollywood Glam",
  "Safari Chic",
  "Rock and Roll Rebel",
  "Boho Beauty",
  "Country Club Casual",
  "Disco Fever Flashback",
  "Preppy and Polished",
  "Chic Safari",
  "Euro Glam",
  "Trendy and Tailored",
  "Modern Minimalism",
  "Classic Hollywood Glam",
  "Grunge Glam",
  "Exotic Elegance",
  "Poolside Chic",
  "Rustic Charm",
  "Chic Lounge Attire",
  "Futuristic Fashion",
  "Wild West Whimsy",
  "Avant-Garde Edge",
  "Island Luxe",
  "Chic Safari",
  "Urban Jungle",
  "Floral Finesse",
  "Neon Nights",
  "Sleek and Sexy",
  "Artsy and Eclectic",
  "Nomadic Elegance",
  "Bohemian Rhapsody",
  "Cruise Chic",
  "Glam Rock",
  "Quirky and Colorful",
  "Riviera Chic",
  "Sophisticated Streetwear",
  "Tropical Glam",
  "Wine Country Casual",
  "Asian Fusion",
  "Retro Futurism",
  "Casual Glam",
  "Tech-Savvy Style",
  "Steampunk Soiree",
  "Glow in the Dark",
  "Whimsical Wonderland"
] as const;

export type TDressCodeType = (typeof DressCode)[number];

export const Music = [
  "EDM",
  "Hip-Hop/Rap",
  "Pop",
  "Rock",
  "R&B",
  "Reggae",
  "Latin",
  "Country",
  "Jazz",
  "Blues",
  "Funk",
  "Soul",
  "House",
  "Techno",
  "Trance",
  "Dubstep",
  "Indie",
  "Alternative",
  "Metal",
  "Classical",
  "Disco",
  "Salsa",
  "Bachata",
  "Merengue",
  "K-Pop",
  "Folk",
  "Gospel",
  "Swing",
  "Ambient",
  "Chillout",
  "Reggaeton",
  "Bluegrass",
  "Fusion",
  "Psychedelic",
  "Jungle",
  "Ska",
  "Grime",
  "Hardcore",
  "Trap",
  "Samba",
  "Acoustic",
  "Dub",
  "Garage",
  "Big Band",
  "Synthwave",
  "Deep House",
  "Nu Disco",
  "Dub Techno",
  "Folk Rock",
  "Trip-Hop",
  "Nu Jazz",
  "Afrobeat",
  "Surf Rock",
  "Rockabilly",
  "Soul Jazz",
  "World Music",
  "Drum and Bass",
  "Hardstyle",
  "Electro Swing",
  "Grunge",
  "Post-Punk",
  "New Wave",
  "Garage Rock",
  "Hard Rock",
  "Punk Rock",
  "Post-Rock",
  "Latin Jazz",
  "Boogie",
  "Future Bass",
  "Trap Soul",
  "Ambient Pop",
  "Post-Disco",
  "Future House",
  "Dream Pop",
  "Minimal Techno",
  "Glitch Hop",
  "Kizomba",
  "Zouk",
  "Electro Pop",
  "Post-Metal",
  "Shoegaze",
  "Vaporwave",
  "Industrial",
  "NeoSoul",
  "New Age",
  "Post-Hardcore"
] as const;

export const Drinks = [
  "Classic Cocktails",
  "Craft Cocktails",
  "Beer Selections",
  "Wine Varieties",
  "Mocktails",
  "Shots and Shooters",
  "Signature Drinks",
  "Frozen Cocktails",
  "Margaritas",
  "Whiskey and Bourbon",
  "Vodka Creations",
  "Rum Cocktails",
  "Tequila Specials",
  "Gin Mixes",
  "Martini Menu",
  "Champagne and Sparkling",
  "Non-Alcoholic Beverages",
  "Ciders and Coolers",
  "Sours and Fizzes",
  "Tropical Libations",
  "Coffee and Espresso Drinks",
  "Irish Drinks",
  "Sake Selections",
  "Local Favorites",
  "House Specials",
  "Infused Spirits",
  "Refreshing Coolers",
  "Cucumber Coolers",
  "Ginger Infusions",
  "Fruity Blends",
  "Spicy Margaritas",
  "Floral Elixirs",
  "Herb-Infused Cocktails",
  "Citrus Delights",
  "Seasonal Specials",
  "Berry Bliss",
  "Coconut Creations",
  "Tiki Cocktails",
  "Smokey Infusions",
  "Prohibition-era Cocktails",
  "Mexican Mixology",
  "Japanese Highballs",
  "Dessert Cocktails",
  "Candy-Inspired Creations",
  "Bourbon Smash",
  "Heritage Classics",
  "Elevated Gin and Tonics",
  "Modern Mixes",
  "Sparkling Sangrias",
  "Aperitifs and Digestifs",
  "Local Distillery Showcases",
  "Aged Spirits",
  "Eco-Friendly Cocktails",
  "Bespoke Creations",
  "Barrel-Aged Cocktails",
  "Artisanal Spirits",
  "Low-ABV Options"
] as const;

export type TDrinkType = (typeof Drinks)[number];

export const Food = [
  "Crispy Chicken Wings",
  "Cheese and Charcuterie Board",
  "Mozzarella Sticks",
  "Loaded Nachos",
  "Sliders (Beef, Chicken, or Veggie)",
  "Spinach Artichoke Dip",
  "Bruschetta",
  "Buffalo Chicken Dip",
  "Quesadillas",
  "Truffle Fries",
  "Spring Rolls",
  "Tacos (Various Fillings)",
  "Shrimp Cocktail",
  "Caprese Skewers",
  "Mini Tacos",
  "Calamari",
  "Hummus Platter",
  "Chicken Satay",
  "Poutine",
  "Garlic Parmesan Fries",
  "Deviled Eggs",
  "Stuffed Jalapeños",
  "Pulled Pork Sliders",
  "Gourmet Pizza Slices",
  "Chips and Salsa",
  "Crab Cakes",
  "Vegetable Spring Rolls",
  "Sushi Rolls",
  "Cheese Quesadillas",
  "Brussels Sprouts with Balsamic Glaze",
  "BBQ Bacon Wrapped Shrimp",
  "Shrimp Tacos",
  "Pita and Dips",
  "Tater Tots",
  "Meatballs",
  "Stuffed Mushrooms",
  "Chicken Tenders",
  "Fried Pickles",
  "BBQ Chicken Flatbread",
  "Mini Corn Dogs",
  "Avocado Toast",
  "Chili Cheese Fries",
  "Edamame",
  "Gourmet Mac and Cheese",
  "Steak Skewers",
  "Garlic Bread",
  "Dumplings",
  "Ceviche",
  "Potato Skins",
  "Cheese Fries",
  "Pulled Chicken Sliders",
  "Onion Rings",
  "Bacon-wrapped Dates",
  "Tuna Tartare",
  "Garlic Knots",
  "Fried Ravioli",
  "Stuffed Bell Peppers"
] as const;

export type TFoodType = (typeof Food)[number];

export const Atmosphere = [
  "Energetic Dance Floor",
  "Chill Lounge Vibes",
  "Live Music Intimacy",
  "Rooftop Serenity",
  "Karaoke Fun Zone",
  "Cozy Jazz Corner",
  "EDM Excitement",
  "Hip-Hop Hangout",
  "Salsa and Latin Heat",
  "Casual Pub Comfort",
  "Retro Arcade Nostalgia",
  "Speakeasy Sophistication",
  "Electronic Beats Haven",
  "Rustic Country Bar",
  "Artistic Bohemian Retreat",
  "Cocktail Connoisseur's Den",
  "Beachfront Relaxation",
  "Rustic Tavern Charm",
  "Clubhouse Party Vibes",
  "Swanky Lounge Luxe"
] as const;
export type TMusicType = (typeof Music)[number];

export const Clubs = [
  "Skyline Lounge",
  "The Velvet Underground",
  "Luxe Horizon Club",
  "Pulse Nightclub",
  "Euphoria Lounge",
  "Electric Avenue Club",
  "The Sapphire Lounge",
  "Infinity Nightclub",
  "Eclipse Club",
  "Enigma Social Club",
  "Midnight Mirage",
  "The Jazz Cellar",
  "Fusion Clubhouse",
  "Neptune's Hideaway",
  "Radiance Social",
  "The Red Velvet Room",
  "Ultraviolet Club",
  "Blissful Beats Club",
  "Stellar Lounge",
  "The Blue Note"
] as const;

export type TClubName = (typeof Clubs)[number];

export const StoreNames = [
  "Fashion Fusion",
  "Tech Haven",
  "Cosmic Trends",
  "Sole Sensation",
  "Gourmet Delights",
  "Style Symphony",
  "Gadget Galaxy",
  "Vogue Vault",
  "Urban Charm",
  "Electro Elegance",
  "Chic Boutique",
  "Gourmet Glory",
  "Luxe Lane",
  "Dazzle Den",
  "Savor Square",
  "Urban Outfits",
  "Tech Terrace",
  "Glitter Galleria",
  "Foodie Fiesta",
  "Elegance Emporium",
  "Sleek Styles",
  "Smart Select",
  "Gourmet Grove",
  "Trendy Trinkets",
  "Flavor Fusion",
  "Epic Elegance",
  "Gadget Garden",
  "Charm City",
  "Gourmet Gateway",
  "Style Sanctuary",
  "Electro Essence",
  "Trend Trance",
  "Gastronomy Grove",
  "Couture Corner",
  "Tech Treasure",
  "Chic Chicane",
  "Gourmet Galore",
  "Urban Utopia",
  "Vivid Vogue",
  "Taste Trail",
  "Epicurean Enclave"
] as const;

export type TStoreNameType = (typeof StoreNames)[number];

export const Sales = [
  "Buy One, Get One Free",
  "Clearance",
  "Flash Sale",
  "Limited-Time Offers",

  "Discount Bonanza",
  "Seasonal Specials",
  "Bundle and Save",
  "Early Bird Discounts",
  "Weekend Blowout",
  "Midnight Madness",
  "Holiday Extravaganza",

  "Student Discounts",
  "Senior Citizen Savings",
  "Cashback Rewards",
  "Refer a Friend Discounts",
  "Loyalty Program Benefits",

  "Cyber Monday Bargains",
  "Black Friday Spectacular",
  "Warehouse Clearance",
  "Last Chance Savings",
  "BOGO 50% Off",
  "Member-Only Discounts",
  "Anniversary",
  "App-Only Offers",
  "Free Shipping on Orders Over $50",
  "Gift with Purchase",
  "Price Drop Alerts",
  "Email Subscriber Exclusives",
  "VIP Previews",
  "Outlet Store Discounts",
  "Savings Spectacle",
  "Major Markdowns",
  "Bundle Bash",
  "Clearance Countdown",
  "Mega Discounts Marathon",
  "Buy More, Save More",
  "Open-Box Specials",
  "End-of-Season Clearance",
  "New Customer Welcome Discounts",
  "Daily Steals",

  "BOGO 30% Off",
  "Reward Points Redemption",
  "Summer Savings Spree",

  "Winter Wonderland Discounts",
  "Spring Fling Savings",

  "Extra 20% Off Items",
  "Sizzling Hot Offers",
  "Mobile App Madness",

  "Frequent Shopper Rewards",
  "Coupon Extravaganza",
  "Secret for Subscribers",
  "Buy Now, Pay Later Options",
  "Digital Download Discounts",

  "Apparel Clearance",
  "Tech Tuesday Discounts",
  "Home Essentials",

  "Beauty Bonanza",
  "Healthy Living Discounts",
  "Entertainment Extravaganza",
  "Travel and Adventure Savings",

  "Gourmet Delights Discounts",
  "Kids' Corner Savings",
  "DIY and Home Improvement Offers",
  "Bookworm Bargains",
  "Gaming Galore Discounts",
  "Fashion Forward",

  "Car Enthusiast Specials",
  "Electronics Expo Discounts"
] as const;

export type TSaleType = (typeof Sales)[number];

export const Deals = [
  "Fitness and Wellness Deals",
  "Pet Paradise Deals",
  "Sports and Outdoor Deals",
  "Limited Quantity Deals",
  "In-Store Exclusive Deals",
  "Deal of the Day",
  "Autumn Harvest Deals",
  "Online Only Deals",
  "Daily Deals",
  "Exclusive Online Deals",
  "Doorbuster Deals"
] as const;

export type TDealType = (typeof Deals)[number];
